2021-07-19 05:04:05,226 [INFO] root consoleworker.py:434	Log file created
2021-07-19 05:04:05,227 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7fe05b3eac10> added
2021-07-19 05:04:05,227 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fe05b432850> added
2021-07-19 05:04:05,227 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7fe05b3d6a50> added
2021-07-19 05:04:05,227 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-07-19_05-04-05.193412
2021-07-19 05:04:05,227 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-07-19 05:04:05,227 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-07-19 05:04:05,227 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-07-19 05:04:05,227 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-07-19 05:04:05,227 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-07-19 05:04:05,227 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin overload from yandextank.plugins.DataUploader
2021-07-19 05:04:05,228 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-07-19 05:04:05,228 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-07-19 05:04:05,228 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-07-19 05:04:05,228 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-07-19 05:04:05,228 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fe05b12ac90>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7fe05b12b1d0>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7fe05b12b310>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7fe05b12b150>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7fe05b12bb50>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7fe05b12a910>, 'plugin_overload': <yandextank.plugins.DataUploader.plugin.Plugin object at 0x7fe05b12afd0>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7fe05b452a10>}
2021-07-19 05:04:05,228 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7fe05b12ac90>
2021-07-19 05:04:05,228 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-07-19 05:04:05,229 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-19_05-04-05.193412/answ_gNUiFG.log
2021-07-19 05:04:05,229 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-19_05-04-05.193412/phout_Hu1Nyj.log
2021-07-19 05:04:05,229 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-19_05-04-05.193412/phantom_stat_dbk1ab.log
2021-07-19 05:04:05,229 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-07-19_05-04-05.193412/phantom_TJafOI.log
2021-07-19 05:04:05,229 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 178.248.237.139:443
2021-07-19 05:04:05,230 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-07-19 05:04:05,230 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('178.248.237.139', 443)), (2, 2, 17, '', ('178.248.237.139', 443)), (2, 3, 0, '', ('178.248.237.139', 443))]
2021-07-19 05:04:05,230 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 178.248.237.139 and port 443
2021-07-19 05:04:10,236 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [178.248.237.139]:443 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2021-07-19 05:04:10,237 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [178.248.237.139]:443
2021-07-19 05:04:10,237 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [178.248.237.139]:443
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [178.248.237.139]:443, use phantom.connection_test=0 to disable it
2021-07-19 05:04:10,237 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 178.248.237.139 and port 443
2021-07-19 05:04:15,241 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [178.248.237.139]:443 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2021-07-19 05:04:15,242 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [178.248.237.139]:443
2021-07-19 05:04:15,242 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [178.248.237.139]:443
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [178.248.237.139]:443, use phantom.connection_test=0 to disable it
2021-07-19 05:04:15,242 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 178.248.237.139 and port 443
2021-07-19 05:04:20,248 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [178.248.237.139]:443 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2021-07-19 05:04:20,248 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [178.248.237.139]:443
2021-07-19 05:04:20,248 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [178.248.237.139]:443
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [178.248.237.139]:443, use phantom.connection_test=0 to disable it
2021-07-19 05:04:20,249 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 178.248.237.139, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-07-19 05:04:20,249 [INFO] root consoleworker.py:269	Trying to clean up
2021-07-19 05:04:20,250 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_GZ2Kzb.lock
2021-07-19 05:04:20,250 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-07-19 05:04:20,250 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-07-19 05:04:20,256 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-07-19 05:04:20,256 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-07-19_05-04-05.193412
2021-07-19 05:04:20,257 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-19_05-04-05.193412/phantom_TJafOI.log to /var/loadtest/logs/2021-07-19_05-04-05.193412/phantom_TJafOI.log
2021-07-19 05:04:20,257 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-19_05-04-05.193412/phantom_TJafOI.log
2021-07-19 05:04:20,257 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-07-19_05-04-05.193412/validation_error.yaml
2021-07-19 05:04:20,257 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-07-19 05:04:20,257 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-19_05-04-05.193412/answ_gNUiFG.log to /var/loadtest/logs/2021-07-19_05-04-05.193412/answ_gNUiFG.log
2021-07-19 05:04:20,257 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-19_05-04-05.193412/answ_gNUiFG.log
2021-07-19 05:04:20,258 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-19_05-04-05.193412/phout_Hu1Nyj.log to /var/loadtest/logs/2021-07-19_05-04-05.193412/phout_Hu1Nyj.log
2021-07-19 05:04:20,258 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-19_05-04-05.193412/phout_Hu1Nyj.log
2021-07-19 05:04:20,258 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-07-19_05-04-05.193412/phantom_stat_dbk1ab.log to /var/loadtest/logs/2021-07-19_05-04-05.193412/phantom_stat_dbk1ab.log
2021-07-19 05:04:20,258 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-07-19_05-04-05.193412/phantom_stat_dbk1ab.log
